import { Inter } from "next/font/google";

import "@/app/styles/globals.css";
const inter = Inter({ subsets: ["latin"] });
import { HeaderTincho } from "@/components/publicaciones/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTincho/>
        {children}
        </body>
    </html>
  );
}
